spring.application.name=ProyectoResidencias

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/proyectoResidencia?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Rutas
app.ruta.base=${APP_RUTA_BASE:uploads/}

app.carpeta.residentes=residentes/
app.carpeta.asesores.internos=asesores-internos/
app.carpeta.asesores.externos=asesores-externos/
app.carpeta.proyectos=proyectos/
app.carpeta.departamentos=departamentos/
app.carpeta.empleados=empleados/

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB
