package itch.tsp.model;

public enum TipoDocumentoResidencia {
	REPORTE_PRELIMINAR,
	PROYECTO_RESIDENCIA,
	PRIMER_INFORME,
	SEGUNDO_INFORME,
	EVALUACION_FINAL,
	PORTADA_REPORTE_FINAL,
	LIBERACION_ASESOR_INTERNO,
	ENTREGA_REPORTE_EMPRESA,
	OFICIO_ENTREGA_DIVISION,
	CARTA_ACEPTACION,
	CARTA_PRESENTACION,
	CARTA_TERMINO
}